github_api_token: "your_token_here"
plot_color: "blue"
plot_title: "Sample Plot"
plot_x_axis_title: "X-axis"
plot_y_axis_title: "Y-axis"
figure_size: [10, 6]
default_save_path: "output_plot.png"
# Add any additional parameters you need for your analysis

